### ISSUE TITLE
Consider alternative OSS license like BOOST? 

### ISSUE THREAD

**Issue by ddiakopoulos** [leonidk/ps1080test#3]
It's a slightly more permissive license. MPL protects you maximally, but BOOST would offer the same protection while offering slightly more leeway in terms of redistribution in commercial or and closed-source software.

**Comment by leonidk** [comment]
I looked it their terms and it'll be MPL for now. Perhaps I'll re-license with something more permissive in the future. 

Boost is a BSD/MIT alternative which doesn't require attribution in binary form. In some ways, that's a step closer to Unlicense or CC0. MPL is BSD/MIT-like for people using the code as-is, and GPL-like for people making modifications. I'm curious what people do with this code and would love to accept and merge modified versions, so MPL appeals to me, as their changes are required to be made available. Boost doesn't protect me in the same way.
